# Generated by Django 4.0.3 on 2022-04-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ONlineLicenceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodgroup', models.CharField(blank=True, max_length=255, null=True)),
                ('citizenshipissuedistrict', models.CharField(blank=True, max_length=255, null=True)),
                ('passportno', models.TextField(blank=True, max_length=255, null=True)),
                ('citizenshipno', models.CharField(blank=True, max_length=255, null=True)),
                ('dateofbirth', models.DateField(blank=True, max_length=255, null=True)),
                ('firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('middlename', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('relationship', models.CharField(blank=True, max_length=255, null=True)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('zone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('contactno', models.TextField(blank=True, max_length=255, null=True)),
                ('officecontactno', models.TextField(blank=True, max_length=255, null=True)),
                ('licensecatagory', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaddocument', models.ImageField(blank=True, null=True, upload_to='upload/image')),
                ('documenttype', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
