# Generated by Django 4.0.3 on 2022-04-04 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='onlinelicenceform',
            table='Online Forms',
        ),
    ]
