# Generated by Django 4.0.3 on 2022-04-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_onlinelicenceform_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinelicenceform',
            name='contactno',
            field=models.BigIntegerField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='onlinelicenceform',
            name='officecontactno',
            field=models.BigIntegerField(blank=True, max_length=255, null=True),
        ),
    ]
