# Generated by Django 4.0.3 on 2022-04-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_onlinelicenceform_contactno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicantid', models.CharField(blank=True, max_length=255, null=True)),
                ('applicantname', models.CharField(blank=True, max_length=255, null=True)),
                ('fathername', models.CharField(blank=True, max_length=255, null=True)),
                ('citizenshipno', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Passed'), (2, 'Fail'), (3, 'Absent')])),
            ],
        ),
    ]
