# Generated by Django 4.0.3 on 2022-04-04 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_notices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notices',
        ),
    ]
