# Generated by Django 4.0.3 on 2022-04-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='examResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicantid', models.CharField(blank=True, max_length=255, null=True)),
                ('applicantname', models.CharField(blank=True, max_length=255, null=True)),
                ('fathername', models.CharField(blank=True, max_length=255, null=True)),
                ('citizenshipno', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Passed', 'Passed'), ('Fail', 'Fail'), ('Absent', 'Absent')], max_length=255)),
            ],
        ),
    ]
